#!/usr/bin/env node
// Interactive first-run initializer — the engine behind `create-vibestack`
// and `pnpm init:app`. Zero dependencies on purpose: it must run right
// after `git clone`, before `pnpm install`.
//
// What it does, in order:
//   1. Asks for your product name → renames @vibestack/* + brand strings.
//   2. Asks which features to enable (billing, email, storage, OAuth,
//      analytics, Sentry, French locale, video swarm).
//   3. Collects API keys for enabled features (every key skippable —
//      the app boots without any of them and degrades gracefully).
//   4. Writes .env with a generated BETTER_AUTH_SECRET.
//   5. Toggles apps/web/src/config/features.ts to match your choices.
//   6. Optionally removes the video swarm package and trims locales.
//   7. Offers to run pnpm install + start Postgres + push the schema.
//
// Non-interactive: node scripts/init.mjs --name my-app --features email,billing --yes

import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";

import { renameBrand } from "./rename.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rl = createInterface({ input: process.stdin, output: process.stdout });

const args = process.argv.slice(2);
const flag = (name) => {
	const i = args.indexOf(`--${name}`);
	return i !== -1 ? args[i + 1] : undefined;
};
const has = (name) => args.includes(`--${name}`);
const NON_INTERACTIVE = has("yes") || has("no-input");

const bold = (s) => `\x1b[1m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const cyan = (s) => `\x1b[36m${s}\x1b[0m`;

async function ask(question, fallback = "") {
	if (NON_INTERACTIVE) return fallback;
	const suffix = fallback ? dim(` (${fallback})`) : "";
	const answer = (await rl.question(`${question}${suffix} `)).trim();
	return answer || fallback;
}

async function confirm(question, fallback = true) {
	if (NON_INTERACTIVE) return fallback;
	const hint = fallback ? "Y/n" : "y/N";
	const answer = (await rl.question(`${question} ${dim(`[${hint}]`)} `))
		.trim()
		.toLowerCase();
	if (!answer) return fallback;
	return answer === "y" || answer === "yes";
}

const FEATURES = [
	{
		key: "email",
		label: "Transactional email (Resend)",
		default: true,
		hint: "off = emails print to the dev console",
	},
	{
		key: "billing",
		label: "Billing (Polar.sh)",
		default: true,
		hint: "subscriptions, checkout, customer portal",
	},
	{
		key: "storage",
		label: "File storage (Cloudflare R2)",
		default: true,
		hint: "user uploads + nightly db backups",
	},
	{
		key: "googleOauth",
		label: "Google sign-in (OAuth)",
		default: false,
		hint: "needs a Google Cloud OAuth client",
	},
	{
		key: "analytics",
		label: "Analytics (PostHog + GA4)",
		default: false,
		hint: "product + web analytics",
	},
	{
		key: "sentry",
		label: "Error tracking (Sentry)",
		default: false,
		hint: "server + client error reporting",
	},
	{
		key: "frenchLocale",
		label: "French locale (next-intl)",
		default: false,
		hint: "off = English-only routing",
	},
	{
		key: "video",
		label: "Video swarm (Remotion reels)",
		default: false,
		hint: "heavy install — Remotion + Chromium deps",
	},
];

async function pickFeatures() {
	const fromFlag = flag("features");
	if (fromFlag !== undefined || NON_INTERACTIVE) {
		const wanted = new Set((fromFlag ?? "email,billing,storage").split(","));
		return Object.fromEntries(FEATURES.map((f) => [f.key, wanted.has(f.key)]));
	}

	const state = Object.fromEntries(FEATURES.map((f) => [f.key, f.default]));
	for (;;) {
		console.log(
			`\n${bold("Features")} — toggle by number, Enter to continue:\n`,
		);
		FEATURES.forEach((f, i) => {
			const mark = state[f.key] ? green("[x]") : "[ ]";
			console.log(`  ${i + 1}. ${mark} ${f.label}  ${dim(f.hint)}`);
		});
		const input = (await rl.question(`\n${cyan("toggle>")} `)).trim();
		if (!input) return state;
		for (const token of input.split(/[\s,]+/)) {
			const idx = Number.parseInt(token, 10) - 1;
			if (FEATURES[idx]) state[FEATURES[idx].key] = !state[FEATURES[idx].key];
		}
	}
}

async function collectKey(label, envName, helpUrl) {
	const value = await ask(
		`  ${label} ${dim(`(${envName}, blank = add later — ${helpUrl})`)}\n  >`,
	);
	return value;
}

function buildEnv({ name, features, keys }) {
	const secret = randomBytes(32).toString("base64");
	const lines = [
		"# Generated by scripts/init.mjs — see .claude/skills/setup/env-reference.md",
		"# Every third-party section is optional: the app boots without it and the",
		"# matching feature degrades gracefully or stays hidden.",
		"",
		"# ── Core ────────────────────────────────────────────────",
		"NODE_ENV=development",
		`DATABASE_URL=postgresql://postgres:password@localhost:5432/${name}`,
		"APP_URL=http://localhost:3001",
		"CORS_ORIGIN=http://localhost:3001",
		`BETTER_AUTH_SECRET=${secret}`,
		"BETTER_AUTH_URL=http://localhost:3001",
		"NEXT_PUBLIC_APP_URL=http://localhost:3001",
		`NEXT_PUBLIC_BRAND_NAME=${name}`,
		"",
	];

	const section = (title, enabled, vars) => {
		lines.push(
			`# ── ${title} ${enabled ? "" : "(disabled — fill in + restart to enable) "}─────────────`,
		);
		for (const [k, v] of vars) {
			lines.push(enabled ? `${k}=${v}` : `# ${k}=${v}`);
		}
		lines.push("");
	};

	section("Email · Resend (https://resend.com)", features.email, [
		["RESEND_API_KEY", keys.RESEND_API_KEY ?? ""],
		["EMAIL_FROM", keys.EMAIL_FROM || `${name} <onboarding@resend.dev>`],
	]);
	section("Billing · Polar (https://polar.sh)", features.billing, [
		["POLAR_ACCESS_TOKEN", keys.POLAR_ACCESS_TOKEN ?? ""],
		["POLAR_SERVER", "sandbox"],
		["POLAR_SUCCESS_URL", "http://localhost:3001/success"],
		["POLAR_PRODUCT_ID_PRO", ""],
		["POLAR_PRODUCT_ID_TEAM", ""],
	]);
	section(
		"Storage · Cloudflare R2 (https://developers.cloudflare.com/r2/)",
		features.storage,
		[
			["R2_ACCOUNT_ID", keys.R2_ACCOUNT_ID ?? ""],
			["R2_ACCESS_KEY_ID", keys.R2_ACCESS_KEY_ID ?? ""],
			["R2_SECRET_ACCESS_KEY", keys.R2_SECRET_ACCESS_KEY ?? ""],
			["R2_BUCKET", keys.R2_BUCKET || name],
			["R2_ENDPOINT", keys.R2_ENDPOINT ?? ""],
		],
	);
	section(
		"Google OAuth (https://console.cloud.google.com)",
		features.googleOauth,
		[
			["GOOGLE_CLIENT_ID", keys.GOOGLE_CLIENT_ID ?? ""],
			["GOOGLE_CLIENT_SECRET", keys.GOOGLE_CLIENT_SECRET ?? ""],
		],
	);
	section("Analytics · PostHog + GA4", features.analytics, [
		["NEXT_PUBLIC_POSTHOG_KEY", keys.NEXT_PUBLIC_POSTHOG_KEY ?? ""],
		["NEXT_PUBLIC_POSTHOG_HOST", "https://us.i.posthog.com"],
		["NEXT_PUBLIC_GA_ID", ""],
	]);
	section("Errors · Sentry (https://sentry.io)", features.sentry, [
		["SENTRY_DSN", keys.SENTRY_DSN ?? ""],
		["NEXT_PUBLIC_SENTRY_DSN", keys.SENTRY_DSN ?? ""],
	]);
	section("Content swarms · Gemini + ElevenLabs (blog + video skills)", false, [
		["GOOGLE_AI_API_KEY", ""],
		["ELEVENLABS_API_KEY", ""],
	]);

	return lines.join("\n");
}

function setFeatureFlag(content, key, enabled) {
	// Matches `<key>: {\n\t\tenabled: <bool>` inside the features object.
	const pattern = new RegExp(
		`(${key}:\\s*\\{\\s*\\n\\s*enabled:\\s*)(true|false)`,
	);
	return content.replace(pattern, `$1${enabled}`);
}

async function main() {
	console.log(`\n${bold("vibestack init")} — let's set up your SaaS.\n`);

	// 1. Product name + rename
	const dirName = ROOT.split("/").at(-1);
	const suggested = /^[a-z][a-z0-9-]*$/.test(dirName) ? dirName : "my-saas";
	const name =
		flag("name") ??
		(await ask(`${bold("Product name")} (lowercase slug):`, suggested));
	if (!/^[a-z][a-z0-9-]*$/.test(name)) {
		console.error(
			`Invalid name "${name}" — lowercase letters, digits, dashes.`,
		);
		process.exit(1);
	}
	if (name !== "vibestack") {
		const { changedFiles } = renameBrand({ from: "vibestack", to: name });
		console.log(
			green(`✓ Renamed vibestack → ${name} in ${changedFiles.length} files`),
		);
	}

	// 2. Feature selection
	const features = await pickFeatures();

	// 3. Keys for enabled features (all skippable)
	const keys = {};
	if (!NON_INTERACTIVE) {
		console.log(
			`\n${bold("API keys")} — paste now or leave blank and fill .env later.\n`,
		);
		if (features.email) {
			keys.RESEND_API_KEY = await collectKey(
				"Resend API key",
				"RESEND_API_KEY",
				"https://resend.com/api-keys",
			);
		}
		if (features.billing) {
			keys.POLAR_ACCESS_TOKEN = await collectKey(
				"Polar access token (sandbox)",
				"POLAR_ACCESS_TOKEN",
				"https://sandbox.polar.sh/settings",
			);
		}
		if (features.storage) {
			keys.R2_ACCOUNT_ID = await collectKey(
				"R2 account id",
				"R2_ACCOUNT_ID",
				"https://dash.cloudflare.com → R2",
			);
			if (keys.R2_ACCOUNT_ID) {
				keys.R2_ACCESS_KEY_ID = await collectKey(
					"R2 access key id",
					"R2_ACCESS_KEY_ID",
					"R2 → Manage API tokens",
				);
				keys.R2_SECRET_ACCESS_KEY = await collectKey(
					"R2 secret access key",
					"R2_SECRET_ACCESS_KEY",
					"same token page",
				);
				keys.R2_BUCKET = await collectKey(
					"R2 bucket name",
					"R2_BUCKET",
					"create one in the R2 dashboard",
				);
				keys.R2_ENDPOINT = `https://${keys.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`;
			}
		}
		if (features.googleOauth) {
			keys.GOOGLE_CLIENT_ID = await collectKey(
				"Google OAuth client id",
				"GOOGLE_CLIENT_ID",
				"https://console.cloud.google.com/apis/credentials",
			);
			keys.GOOGLE_CLIENT_SECRET = await collectKey(
				"Google OAuth client secret",
				"GOOGLE_CLIENT_SECRET",
				"same page",
			);
		}
		if (features.analytics) {
			keys.NEXT_PUBLIC_POSTHOG_KEY = await collectKey(
				"PostHog project key",
				"NEXT_PUBLIC_POSTHOG_KEY",
				"https://posthog.com",
			);
		}
		if (features.sentry) {
			keys.SENTRY_DSN = await collectKey(
				"Sentry DSN",
				"SENTRY_DSN",
				"https://sentry.io",
			);
		}
	}

	// 4. Write .env
	const envPath = join(ROOT, ".env");
	if (existsSync(envPath)) {
		const overwrite = await confirm(
			"\n.env already exists — overwrite?",
			false,
		);
		if (overwrite) writeFileSync(envPath, buildEnv({ name, features, keys }));
		else console.log(dim("  keeping existing .env"));
	} else {
		writeFileSync(envPath, buildEnv({ name, features, keys }));
		console.log(green("✓ Wrote .env (BETTER_AUTH_SECRET generated)"));
	}

	// 5. Toggle features.ts — billing + files tabs follow your choices.
	const featuresPath = join(ROOT, "apps/web/src/config/features.ts");
	let featuresSrc = readFileSync(featuresPath, "utf8");
	featuresSrc = setFeatureFlag(featuresSrc, "billing", features.billing);
	featuresSrc = setFeatureFlag(featuresSrc, "files", features.storage);
	writeFileSync(featuresPath, featuresSrc);
	console.log(green("✓ Updated apps/web/src/config/features.ts"));

	// 6a. Locales
	if (!features.frenchLocale) {
		const i18nPath = join(ROOT, "packages/i18n/src/index.ts");
		const i18nSrc = readFileSync(i18nPath, "utf8");
		writeFileSync(i18nPath, i18nSrc.replace(`["en", "fr"]`, `["en"]`));
		console.log(green("✓ English-only locale routing"));
	}

	// 6b. Video swarm
	if (!features.video) {
		rmSync(join(ROOT, "packages/video"), { recursive: true, force: true });
		rmSync(join(ROOT, ".claude/skills/video-writer"), {
			recursive: true,
			force: true,
		});
		const pkgPath = join(ROOT, "package.json");
		const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
		for (const script of Object.keys(pkg.scripts)) {
			if (script.startsWith("reel:")) delete pkg.scripts[script];
		}
		writeFileSync(pkgPath, `${JSON.stringify(pkg, null, "\t")}\n`);
		console.log(
			green("✓ Removed video swarm (packages/video + reel:* scripts + skill)"),
		);
	}

	// 7. Install + database
	const run = (cmd) => {
		console.log(dim(`\n$ ${cmd}`));
		execSync(cmd, { cwd: ROOT, stdio: "inherit" });
	};

	if (
		!has("skip-install") &&
		(await confirm(`\nRun ${bold("pnpm install")} now?`, true))
	) {
		run("pnpm install");
		if (await confirm("Start Postgres (Docker) + push the schema?", true)) {
			run("pnpm db:start");
			run("pnpm db:push");
		}
	}

	console.log(`
${bold(green("Done."))} Next steps:

  ${cyan("pnpm dev")}            ${dim("# web :3001 · marketing :3000 · admin :3002")}
  ${cyan("pnpm dev:web")}        ${dim("# just the product app")}

Inside Claude Code:
  ${cyan("/setup")}              ${dim("# finish configuring keys conversationally")}
  ${cyan("/grill-with-docs")}    ${dim("# start designing your first feature")}

Enable a skipped feature later: fill its section in .env, flip the toggle
in apps/web/src/config/features.ts, restart pnpm dev.
`);
	rl.close();
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
